apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxaffinityapp
spec:
  selector:
    matchLabels:
      app: nginxaffinityapp
  template:
    metadata:
      labels:
        app: nginxaffinityapp
    spec:
      affinity:
        nodeAffinity: 
         requiredDuringSchedulingIgnoredDuringExecution: 
          nodeSelectorTerms:
          - matchExpressions: 
            - key: disktype
              operator: In
              values: 
              - ssd
      containers:
      - name: nginxaffinityapp
        image: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginxdemoappsvc
spec:
  selector:
    app: nginxaffinityapp
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer

